### ISSUE TITLE
It dosnt save the map 

### ISSUE THREAD

**Issue by laura727** [ndee85/Multi-Object-UV-Editing#11]
as soon as I press tab the UV map that I just created ceases to exist and returns to the old individual maps

**Comment by laura727** [comment]
It seems to be particularly affecting 2 objects not others - These become hidden when I press tab

**Comment by ndee85** [comment]
@laura727 
it makes duplicates of the objects and merges those where you edit the uvs. After leaving the Editmode it transfers those uvs to your original ones. At least thats how it is supposed to work.

It seems there occurs a problem. Could you please provide a file which fails and I can take a closer look.

Best regards,
Andreas

**Comment by laura727** [comment]
I'm having trouble attaching the file 
This site isnt accepting the zipped file

**Comment by laura727** [comment]
Do you have an email I could send it to?

**Comment by laura727** [comment]
Sorry for the trouble - I dont usualy use git hub so I'm not actualy suree how to transfer the file without being able to just attach it to the chat

**Comment by ndee85** [comment]
@laura727 
just drop your file here:
https://cloud.esau.me/index.php/s/ypeK7ZezdkkMsmd

**Comment by ndee85** [comment]
Issue should be fixed. Please try the latest version from github.

**Comment by laura727** [comment]
Great I'll give it a try - thanks for the speedy service ;D
