### ISSUE TITLE
None object has no "mode" attribute

### ISSUE THREAD

**Issue by simon50keda** [ndee85/Multi-Object-UV-Editing#4]
Hi,

as far as I like idea of this add-on, I would also like to be "bullet" proof.

So to reproduce no "mode" attribute found error do this:
1. go to multi object uvu editing as normally
2. in outliner select some third object that is currently not in edit mode

Hopefully it's not a big deal in the code :)

**Comment by ndee85** [comment]
This issue is fixed with the latest commit. Thanks for reporting.
