### ISSUE TITLE
Crash Blender when using on object with no UV maps

### ISSUE THREAD

**Issue by gregzaal** [ndee85/Multi-Object-UV-Editing#5]
If the objects you've got selected have no UV Maps at all when clicking the button, Blender crashes to desktop :(

Would be nice to create a new empty UV Map for them, and throw a warning or info message to say that you did. (self.report...)

**Comment by ndee85** [comment]
Hi Greg.. It did usually.. I will check on that. Thanks for reporting :)

**Comment by gregzaal** [comment]
Thanks man :)

**Comment by ndee85** [comment]
Ok.. fixed this crash. It still does not create a uv map, since I wanted to have the user the control if he adds a uv or not.

**Comment by gregzaal** [comment]
:+1:
