### ISSUE TITLE
Crash with a rotate object

### ISSUE THREAD

**Issue by stilobique** [ndee85/Multi-Object-UV-Editing#6]
Hi,
my blender crash with a simple scene ; one object is turn. Try with the last update.

You can open my .blend, the object "poignet" (https://www.dropbox.com/s/wrfjdrdmlsdi8fs/Assets_Props_Parking.blend?dl=0)

**Comment by ndee85** [comment]
ok.. this bug is fixed. This crash happened when objects were in local view. The joining operator didn't work properly.
b556fd1aa93599ab424072df5e4af865ba937fe3
